FROM devbeta/mariadb:10.3.9  

LABEL name="ASH+MariaDB"
LABEL nodeType="ash-mariadb"
LABEL nodeTypeAlias=""
LABEL cluster="https://raw.githubusercontent.com/annajel/mariadb/master/10.3.9-cluster.json"
